// Hidden topic tree used to vary generated texts: for every exercise the
// server draws one subtheme of the chosen theme, then one of its ten
// angles (lib/ai.ts). The learner only ever picks the theme — none of this
// is shown in the UI. Angles are kept broad enough to work at every level
// (A2–C1) and for every text type.

export const THEME_TREE: Record<string, Record<string, string[]>> = {
  "Science et nouvelle technologie": {
    "Intelligence artificielle": [
      "assistants conversationnels au quotidien",
      "IA et création artistique",
      "IA à l'école et triche",
      "IA et emploi",
      "voitures autonomes",
      "deepfakes et désinformation",
      "IA en médecine",
      "biais des algorithmes",
      "régulation de l'IA",
      "relation affective avec une machine",
    ],
    "Astronomie et espace": [
      "retour sur la Lune",
      "conquête de Mars",
      "tourisme spatial",
      "satellites et débris",
      "télescopes et exoplanètes",
      "vie extraterrestre",
      "astronautes et vie en orbite",
      "éclipses et phénomènes célestes",
      "course à l'espace entre puissances",
      "pollution lumineuse et ciel étoilé",
    ],
    "Médecine et santé": [
      "vaccins et innovations",
      "greffes d'organes",
      "cancer et nouveaux traitements",
      "télémédecine",
      "antibiotiques et résistances",
      "déserts médicaux",
      "médecine personnalisée",
      "chirurgie assistée par robot",
      "maladies rares",
      "prix des médicaments",
    ],
    "Génétique et ADN": [
      "tests ADN grand public",
      "thérapie génique",
      "modification des embryons",
      "OGM et alimentation",
      "clonage",
      "ADN et enquêtes policières",
      "maladies héréditaires",
      "résurrection d'espèces disparues",
      "généalogie et origines",
      "éthique de la sélection génétique",
    ],
    "Neurosciences et cerveau": [
      "sommeil et rêves",
      "mémoire et oubli",
      "addiction aux écrans",
      "implants cérébraux",
      "cerveau des adolescents",
      "maladie d'Alzheimer",
      "émotions et prise de décision",
      "plasticité et apprentissage",
      "méditation et cerveau",
      "bilinguisme",
    ],
    "Robotique et automatisation": [
      "robots dans les usines",
      "robots domestiques",
      "robots d'assistance aux personnes âgées",
      "livraison par drones",
      "caisses automatiques",
      "robots humanoïdes",
      "exosquelettes",
      "robots dans l'agriculture",
      "robots militaires",
      "métiers menacés par l'automatisation",
    ],
    "Cybersécurité et données personnelles": [
      "piratage d'entreprises",
      "rançongiciels contre les hôpitaux",
      "arnaques en ligne",
      "mots de passe et identité numérique",
      "surveillance de masse",
      "reconnaissance faciale",
      "cookies et publicité ciblée",
      "droit à l'oubli",
      "cyberguerre entre États",
      "protection des données des enfants",
    ],
    "Énergie et innovations (batteries, fusion, hydrogène)": [
      "batteries des voitures électriques",
      "fusion nucléaire",
      "hydrogène vert",
      "stockage de l'énergie",
      "réseaux électriques intelligents",
      "panneaux solaires de nouvelle génération",
      "petits réacteurs nucléaires",
      "métaux rares et recyclage",
      "sobriété énergétique",
      "coupures et pannes géantes",
    ],
    "Ordinateurs quantiques": [
      "principe expliqué simplement",
      "course mondiale au quantique",
      "cryptographie menacée",
      "découverte de médicaments",
      "simulation des matériaux",
      "start-up du quantique",
      "investissements publics",
      "limites et promesses exagérées",
      "ordinateur quantique et climat",
      "métiers de demain",
    ],
    "Objets connectés et vie numérique": [
      "maison connectée",
      "montres et santé connectée",
      "enceintes vocales",
      "smartphone et dépendance",
      "ville intelligente",
      "voitures connectées",
      "jouets connectés",
      "télétravail et outils numériques",
      "fracture numérique",
      "déconnexion volontaire",
    ],
  },

  Environnement: {
    "Changement climatique": [
      "vagues de chaleur",
      "fonte des glaciers",
      "montée des océans",
      "réfugiés climatiques",
      "COP et accords internationaux",
      "éco-anxiété",
      "adaptation des villes",
      "climatosceptiques",
      "empreinte carbone individuelle",
      "procès climatiques",
    ],
    "Biodiversité et espèces menacées": [
      "disparition des abeilles",
      "retour du loup",
      "parcs nationaux",
      "braconnage",
      "espèces invasives",
      "oiseaux en déclin",
      "récifs coralliens",
      "zoos et conservation",
      "réensauvagement",
      "biodiversité en ville",
    ],
    "Énergies renouvelables": [
      "éoliennes et paysages",
      "fermes solaires",
      "hydroélectricité",
      "géothermie",
      "énergie des vagues",
      "communautés énergétiques locales",
      "biogaz",
      "sortie du charbon",
      "emplois verts",
      "opposition locale aux projets",
    ],
    "Pollution de l'air": [
      "pics de pollution urbaine",
      "zones à faibles émissions",
      "pollution intérieure",
      "asthme et santé des enfants",
      "transports et pollution",
      "chauffage au bois",
      "pollution industrielle",
      "capteurs citoyens",
      "pollution et inégalités",
      "villes sans voitures",
    ],
    "Gestion de l'eau": [
      "sécheresses",
      "méga-bassines",
      "eau potable",
      "inondations",
      "dessalement",
      "fuites et gaspillage",
      "eau et agriculture",
      "conflits pour l'eau",
      "rivières polluées",
      "eau en bouteille ou du robinet",
    ],
    Déforestation: [
      "Amazonie",
      "huile de palme",
      "incendies de forêt",
      "reboisement",
      "bois illégal",
      "forêts et peuples autochtones",
      "soja et élevage",
      "forêts urbaines",
      "certification du bois",
      "forêt et puits de carbone",
    ],
    "Océans et pollution plastique": [
      "continent de plastique",
      "microplastiques",
      "surpêche",
      "aires marines protégées",
      "nettoyage des plages",
      "plastique à usage unique",
      "navires et pollution",
      "animaux marins piégés",
      "exploitation minière des fonds marins",
      "traité mondial sur le plastique",
    ],
    "Agriculture durable": [
      "agriculture biologique",
      "pesticides",
      "circuits courts",
      "élevage intensif",
      "régime végétarien",
      "agriculteurs en difficulté",
      "agriculture urbaine",
      "sols et érosion",
      "gaspillage alimentaire",
      "semences paysannes",
    ],
    "Recyclage et économie circulaire": [
      "tri des déchets",
      "réparation des objets",
      "obsolescence programmée",
      "vêtements de seconde main",
      "consigne des bouteilles",
      "déchets électroniques",
      "compost",
      "zéro déchet",
      "recyclage des batteries",
      "location plutôt qu'achat",
    ],
    "Catastrophes naturelles": [
      "séismes",
      "ouragans",
      "tsunamis",
      "éruptions volcaniques",
      "inondations éclair",
      "glissements de terrain",
      "alertes et prévention",
      "reconstruction après la catastrophe",
      "assurances et catastrophes",
      "solidarité internationale",
    ],
  },

  Économie: {
    "Inflation et pouvoir d'achat": [
      "prix de l'alimentation",
      "facture d'énergie",
      "salaires et inflation",
      "prix de l'essence",
      "petits budgets étudiants",
      "promotions et consommation",
      "rétrécissement des produits",
      "aides de l'État",
      "épargne qui fond",
      "coût des vacances",
    ],
    "Marchés financiers et Bourse": [
      "krach boursier",
      "actionnaires particuliers",
      "placements des jeunes",
      "bulles spéculatives",
      "introduction en Bourse",
      "fonds de pension",
      "Bourse et climat",
      "délits d'initiés",
      "rôle des agences de notation",
      "applications de trading",
    ],
    "Emploi et chômage": [
      "chômage des jeunes",
      "métiers en pénurie",
      "reconversion professionnelle",
      "intérim et précarité",
      "plateformes et autoentrepreneurs",
      "licenciements économiques",
      "entretien d'embauche",
      "apprentissage",
      "semaine de quatre jours",
      "grande démission",
    ],
    "Commerce international": [
      "guerres commerciales",
      "droits de douane",
      "porte-conteneurs et ports",
      "délocalisations et relocalisations",
      "made in France",
      "accords de libre-échange",
      "dépendance aux importations",
      "pénuries mondiales",
      "contrefaçon",
      "commerce équitable",
    ],
    "Cryptomonnaies et finance numérique": [
      "bitcoin",
      "arnaques crypto",
      "paiement sans contact",
      "néobanques",
      "monnaie numérique des banques centrales",
      "NFT",
      "minage et énergie",
      "régulation des cryptos",
      "paiement fractionné",
      "disparition des espèces",
    ],
    "Entrepreneuriat et startups": [
      "créer son entreprise",
      "licornes",
      "levées de fonds",
      "incubateurs",
      "échec et rebond",
      "entrepreneuriat féminin",
      "startups à impact",
      "franchise",
      "reprise d'entreprise familiale",
      "jeunes entrepreneurs",
    ],
    "Fiscalité et impôts": [
      "impôt sur le revenu",
      "TVA",
      "évasion fiscale",
      "paradis fiscaux",
      "taxe sur les plus riches",
      "impôts locaux",
      "fraude fiscale",
      "niches fiscales",
      "taxe carbone",
      "consentement à l'impôt",
    ],
    "Immobilier et logement": [
      "prix des loyers",
      "accès à la propriété",
      "logement étudiant",
      "colocation",
      "logements vides",
      "mal-logement",
      "locations touristiques de courte durée",
      "rénovation énergétique",
      "crédit immobilier",
      "exode vers les campagnes",
    ],
    "Banques centrales et politique monétaire": [
      "taux d'intérêt",
      "lutte contre l'inflation",
      "indépendance des banques centrales",
      "euro",
      "planche à billets",
      "crédit plus cher",
      "faillites bancaires",
      "réserves d'or",
      "récession",
      "confiance dans la monnaie",
    ],
    "Inégalités et répartition des richesses": [
      "écart des salaires",
      "grandes fortunes",
      "pauvreté",
      "héritage",
      "écart entre territoires",
      "égalité des chances",
      "revenu universel",
      "inégalités face à la santé",
      "banques alimentaires",
      "philanthropie",
    ],
  },

  Société: {
    "Éducation et école": [
      "harcèlement scolaire",
      "écrans en classe",
      "devoirs à la maison",
      "classes surchargées",
      "métier d'enseignant",
      "orientation scolaire",
      "grandes écoles et prépas",
      "uniforme",
      "école à la maison",
      "décrochage scolaire",
    ],
    "Santé publique": [
      "obésité",
      "tabac et vapotage",
      "alcool chez les jeunes",
      "santé mentale",
      "épidémies",
      "dépistage",
      "sport et santé",
      "hôpital sous tension",
      "alimentation et santé",
      "prévention routière",
    ],
    "Égalité femmes-hommes": [
      "écart de salaire",
      "femmes dirigeantes",
      "violences conjugales",
      "partage des tâches domestiques",
      "femmes dans les sciences",
      "sexisme ordinaire",
      "congé parental",
      "sport féminin",
      "représentation dans les médias",
      "parité en politique",
    ],
    "Famille et parentalité": [
      "familles recomposées",
      "famille monoparentale",
      "congé paternité",
      "grands-parents",
      "adoption",
      "natalité en baisse",
      "éducation positive",
      "écrans et enfants",
      "conciliation travail-famille",
      "adolescents et parents",
    ],
    "Jeunesse et génération Z": [
      "premier emploi",
      "logement des jeunes",
      "engagement pour le climat",
      "influenceurs",
      "rapport au travail",
      "études à l'étranger",
      "santé mentale des jeunes",
      "vote des jeunes",
      "fête et sociabilité",
      "consommation responsable",
    ],
    "Réseaux sociaux et numérique": [
      "influenceurs et publicité",
      "cyberharcèlement",
      "fausses informations",
      "algorithmes et bulles",
      "réseaux sociaux et estime de soi",
      "âge minimum",
      "vie privée en ligne",
      "célébrité virale",
      "créateurs de contenu",
      "détox numérique",
    ],
    "Travail et télétravail": [
      "télétravail",
      "burn-out",
      "open space",
      "semaine de quatre jours",
      "retraite",
      "syndicats et grèves",
      "travail de nuit",
      "nomades numériques",
      "management bienveillant",
      "sens du travail",
    ],
    "Religion et laïcité": [
      "laïcité à l'école",
      "signes religieux",
      "fêtes religieuses",
      "dialogue interreligieux",
      "déclin de la pratique",
      "religion et réseaux sociaux",
      "liberté d'expression et blasphème",
      "patrimoine religieux",
      "spiritualité sans religion",
      "religion et politique",
    ],
    "Vieillissement de la population": [
      "maisons de retraite",
      "aidants familiaux",
      "retraites",
      "solitude des personnes âgées",
      "seniors et numérique",
      "allongement de l'espérance de vie",
      "travailler plus longtemps",
      "cohabitation entre générations",
      "maladies du grand âge",
      "tourisme des seniors",
    ],
    "Justice et criminalité": [
      "prisons surpeuplées",
      "délinquance des mineurs",
      "police et citoyens",
      "erreurs judiciaires",
      "cybercriminalité",
      "trafic de drogue",
      "justice restaurative",
      "vidéosurveillance",
      "procès médiatiques",
      "réinsertion des détenus",
    ],
  },

  "Civilisation anglophone": {
    "Institutions britanniques": [
      "rôle du monarque",
      "Chambre des communes",
      "Chambre des lords",
      "Premier ministre et 10 Downing Street",
      "constitution non écrite",
      "Prime Minister's Questions",
      "fonction publique britannique",
      "système électoral uninominal",
      "BBC et service public",
      "couronnement et rituels royaux",
    ],
    "Brexit et ses conséquences": [
      "référendum de 2016",
      "négociations avec l'UE",
      "frontière irlandaise",
      "pêche et Brexit",
      "étudiants et programme Erasmus",
      "contrôles aux frontières",
      "économie après le Brexit",
      "citoyens européens au Royaume-Uni",
      "regret du Brexit (« Bregret »)",
      "nouvelles relations commerciales",
    ],
    "Unité du Royaume-Uni": [
      "indépendantisme écossais",
      "Parlement écossais",
      "pays de Galles et langue galloise",
      "accord du Vendredi saint",
      "réunification irlandaise",
      "dévolution des pouvoirs",
      "identité anglaise",
      "fractures Nord-Sud en Angleterre",
      "symboles du Royaume-Uni",
      "Londres face au reste du pays",
    ],
    "Système politique américain": [
      "rôle du président",
      "Congrès",
      "Cour suprême",
      "fédéralisme et droits des États",
      "Constitution et amendements",
      "procédure de destitution",
      "lobbying",
      "pouvoirs des gouverneurs",
      "décrets présidentiels",
      "contre-pouvoirs",
    ],
    "Élections et polarisation aux États-Unis": [
      "primaires",
      "collège électoral",
      "démocrates et républicains",
      "campagnes et financement",
      "désinformation électorale",
      "participation et droit de vote",
      "découpage des circonscriptions",
      "États-clés",
      "débats télévisés",
      "fractures entre villes et campagnes",
    ],
    "Questions raciales et droits civiques": [
      "héritage de l'esclavage",
      "ségrégation et lois Jim Crow",
      "Martin Luther King et le mouvement des droits civiques",
      "Black Lives Matter",
      "violences policières",
      "discrimination positive",
      "droits des peuples autochtones",
      "inégalités de richesse",
      "réparations",
      "mémoire et statues",
    ],
    "Débats de société américains": [
      "armes à feu",
      "avortement",
      "peine de mort",
      "liberté d'expression sur les campus",
      "religion dans la vie publique",
      "drogues et légalisation",
      "droits LGBTQ+",
      "prisons privées",
      "guerres culturelles",
      "interdiction de livres",
    ],
    "Santé et protection sociale": [
      "NHS",
      "Obamacare",
      "coût des soins aux États-Unis",
      "assurance maladie privée",
      "crise des opioïdes",
      "listes d'attente au NHS",
      "Medicare et Medicaid",
      "prix des médicaments",
      "protection sociale britannique",
      "grèves des soignants",
    ],
    "Immigration et multiculturalisme": [
      "frontière mexicaine",
      "génération Windrush",
      "rêve américain",
      "sans-papiers",
      "traversées de la Manche",
      "multiculturalisme britannique",
      "communautés indiennes et pakistanaises au Royaume-Uni",
      "visas et citoyenneté",
      "réfugiés",
      "assimilation ou intégration",
    ],
    "Le monde anglophone et l'héritage de l'Empire": [
      "Commonwealth",
      "« special relationship »",
      "décolonisation",
      "Inde et Royaume-Uni",
      "Australie et Nouvelle-Zélande",
      "Canada",
      "l'anglais langue mondiale",
      "soft power américain",
      "OTAN et alliances",
      "mémoire coloniale",
    ],
  },
};
